### ISSUE TITLE
error about use ',dd'

### ISSUE THREAD

**Issue by ayakira** [hsitz/VimOrganizer#79]
unknow function: calendar#show

**Comment by hsitz** [comment]
On Mon, Nov 23, 2015 at 12:57 AM, ayakira <notifications@github.com> wrote:

> unknow function: calendar#show
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hsitz/VimOrganizer/issues/79>.
>
This error probably  means you don't have the calendar.vim plugin
installed.  You can find it here:
http://www.vim.org/scripts/script.php?script_id=52

**Comment by ayakira** [comment]
thank you hsitz, i get it.  i used the  calendar.vim on github. so vim report the error. when i use the calendar.vim on http://www.vim.org/scripts/script.php?script_id=52. i work well. thanks again.
