### ISSUE TITLE
is this VimOrganizer mode still being used (and maintained?)

### ISSUE THREAD

**Issue by TheBigBear** [hsitz/VimOrganizer#80]
Hi Herb,
Do you still use this? I for one have moved on and am not using it anymore. Is it worth keeping this up? There doesn't seem to be any activity or merging of PRs for quite some time now?

**Comment by TheBigBear** [comment]
It doesn't do any harm to have this up on githbub of course. and maybe one day I might want to re-visit this. ;-)

**Comment by hsitz** [comment]
On Mon, Jun 6, 2016 at 1:29 PM, TheBigBear <notifications@github.com> wrote:

> It doesn't do any harm to have this up on githbub of course. and maybe one
> day I might want to re-visit this. ;-)
>
>
No, I'm not using it anymore and not maintaining.  I guess I should add a
note in the readme. . . .
